// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Data.Migrations
{
    [DbContext(typeof(PharmacyContext))]
    partial class PharmacyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Address")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Description");

                    b.Property<int>("Id_City")
                        .HasColumnType("int");

                    b.Property<int>("Id_person")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_City");

                    b.HasIndex("Id_person");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Buy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_buy")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("Buy_date");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("int");

                    b.Property<int>("Provider_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("Provider_Id");

                    b.ToTable("Buy", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_category")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "D"
                        });
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_city")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_department")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Id_department");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Id_department = 1,
                            Name = "Medellin"
                        },
                        new
                        {
                            Id = 2,
                            Id_department = 1,
                            Name = "Apartado"
                        },
                        new
                        {
                            Id = 3,
                            Id_department = 1,
                            Name = "Arboletes"
                        },
                        new
                        {
                            Id = 4,
                            Id_department = 1,
                            Name = "Rio negro"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_contact")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Description");

                    b.Property<int>("Id_contact_category")
                        .HasColumnType("int");

                    b.Property<int>("Id_contact_type")
                        .HasColumnType("int");

                    b.Property<int>("Id_person")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_contact_category");

                    b.HasIndex("Id_contact_type");

                    b.HasIndex("Id_person");

                    b.ToTable("Contact", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "contacto@proveedor_A.com",
                            Id_contact_category = 1,
                            Id_contact_type = 2,
                            Id_person = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "contacto@proveedor_B.com",
                            Id_contact_category = 1,
                            Id_contact_type = 2,
                            Id_person = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "contacto@proveedor_C.com",
                            Id_contact_category = 1,
                            Id_contact_type = 2,
                            Id_person = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Contact_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_contactType")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Contact_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "staff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "profesional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Provider"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Contact_category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_contactCategory")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Contact_category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 3,
                            Name = "telepathic"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_country")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Colombia"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Department")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_country")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Id_country");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Id_country = 1,
                            Name = "Antioquia"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Detail_buy", b =>
                {
                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("Buy_Id")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("MedicineId", "Buy_Id");

                    b.HasIndex("Buy_Id");

                    b.ToTable("Detail_Buy", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Detail_sale", b =>
                {
                    b.Property<int>("Id_medicine")
                        .HasColumnType("int");

                    b.Property<int>("Id_sale")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id_medicine", "Id_sale");

                    b.HasIndex("Id_sale");

                    b.ToTable("Detail_Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Document_type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Document_type")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("Document_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "CC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "TI"
                        },
                        new
                        {
                            Id = 3,
                            Description = "NIT"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Employee")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonId = 6,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            PersonId = 8,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 3,
                            PersonId = 9,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 4,
                            PersonId = 10,
                            PositionId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Employee_eps", b =>
                {
                    b.Property<int>("EpsId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("EpsId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Employee_Eps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Eps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Eps")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Person")
                        .HasColumnType("int");

                    b.Property<int>("Id_type_eps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Person");

                    b.HasIndex("Id_type_eps");

                    b.ToTable("Eps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Inventory")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_MedicineInfo")
                        .HasColumnType("int");

                    b.Property<string>("Name_medicine")
                        .HasColumnType("longtext");

                    b.Property<int>("Total_stock")
                        .HasColumnType("int")
                        .HasColumnName("Total_Stock");

                    b.Property<int>("Ubication")
                        .HasColumnType("int")
                        .HasColumnName("Ubication");

                    b.HasKey("Id");

                    b.HasIndex("Id_MedicineInfo");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Id_MedicineInfo = 1,
                            Total_stock = 5,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 2,
                            Id_MedicineInfo = 2,
                            Total_stock = 6,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 3,
                            Id_MedicineInfo = 3,
                            Total_stock = 9,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 4,
                            Id_MedicineInfo = 4,
                            Total_stock = 6,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 5,
                            Id_MedicineInfo = 5,
                            Total_stock = 3,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 6,
                            Id_MedicineInfo = 6,
                            Total_stock = 4,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 7,
                            Id_MedicineInfo = 7,
                            Total_stock = 7,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 8,
                            Id_MedicineInfo = 8,
                            Total_stock = 8,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 9,
                            Id_MedicineInfo = 9,
                            Total_stock = 2,
                            Ubication = 4
                        },
                        new
                        {
                            Id = 10,
                            Id_MedicineInfo = 10,
                            Total_stock = 4,
                            Ubication = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Medicine")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_creation")
                        .HasColumnType("DateTime")
                        .HasColumnName("Date_creation");

                    b.Property<DateTime>("Date_expiration")
                        .HasColumnType("DateTime")
                        .HasColumnName("Date_expiration");

                    b.Property<int>("Id_Inventory")
                        .HasColumnType("int");

                    b.Property<int>("Id_state")
                        .HasColumnType("int");

                    b.Property<string>("Name_medicine")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id_Inventory");

                    b.HasIndex("Id_state");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Medicine_brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Medicine_brand")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Medicine_brand", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TQ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "La Sante"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Durafex"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ferrer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bayer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Genfar"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Medicine_info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Position")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Description");

                    b.Property<int>("Discount")
                        .HasColumnType("int")
                        .HasColumnName("Discount");

                    b.Property<int>("Id_Category")
                        .HasColumnType("int");

                    b.Property<int>("Id_MedicineBrand")
                        .HasColumnType("int");

                    b.Property<int>("Id_Presentation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<bool>("Need_order")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Need_Order");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.HasIndex("Id_Category");

                    b.HasIndex("Id_MedicineBrand");

                    b.HasIndex("Id_Presentation");

                    b.ToTable("MedicineInfo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Alivia el dolor leve y moderado,\nVia oral 10 comprimidos",
                            Discount = 0,
                            Id_Category = 1,
                            Id_MedicineBrand = 5,
                            Id_Presentation = 1,
                            Name = "Paracetamol",
                            Need_order = true,
                            Price = 20
                        },
                        new
                        {
                            Id = 2,
                            Description = "30 tabletas cubiertas de 1g",
                            Discount = 5,
                            Id_Category = 1,
                            Id_MedicineBrand = 2,
                            Id_Presentation = 1,
                            Name = "Ibuprofeno",
                            Need_order = true,
                            Price = 25
                        },
                        new
                        {
                            Id = 3,
                            Description = "104 tabletas de 100mg",
                            Discount = 10,
                            Id_Category = 1,
                            Id_MedicineBrand = 5,
                            Id_Presentation = 1,
                            Name = "Aspirina",
                            Need_order = true,
                            Price = 15
                        },
                        new
                        {
                            Id = 4,
                            Description = "50 capsulas 500mg",
                            Discount = 0,
                            Id_Category = 1,
                            Id_MedicineBrand = 3,
                            Id_Presentation = 3,
                            Name = "Amoxicilina",
                            Need_order = true,
                            Price = 40
                        },
                        new
                        {
                            Id = 5,
                            Description = "10 tabletas 10mg",
                            Discount = 0,
                            Id_Category = 1,
                            Id_MedicineBrand = 7,
                            Id_Presentation = 1,
                            Name = "Cetirizina",
                            Need_order = true,
                            Price = 10
                        },
                        new
                        {
                            Id = 6,
                            Description = "30 tabletas recubiertas de 50mg via oral",
                            Discount = 0,
                            Id_Category = 1,
                            Id_MedicineBrand = 7,
                            Id_Presentation = 1,
                            Name = "Losartan",
                            Need_order = true,
                            Price = 55
                        },
                        new
                        {
                            Id = 7,
                            Description = "30 tabletas de 850mg",
                            Discount = 40,
                            Id_Category = 1,
                            Id_MedicineBrand = 2,
                            Id_Presentation = 1,
                            Name = "Metformina",
                            Need_order = true,
                            Price = 60
                        },
                        new
                        {
                            Id = 8,
                            Description = "30 tabletas recubiertas de 30mg",
                            Discount = 12,
                            Id_Category = 1,
                            Id_MedicineBrand = 3,
                            Id_Presentation = 1,
                            Name = "Atorvastatina",
                            Need_order = true,
                            Price = 45
                        },
                        new
                        {
                            Id = 9,
                            Description = "30 tabletas recubiertas de 2mg",
                            Discount = 0,
                            Id_Category = 1,
                            Id_MedicineBrand = 1,
                            Id_Presentation = 1,
                            Name = "Clonazepam",
                            Need_order = true,
                            Price = 35
                        },
                        new
                        {
                            Id = 10,
                            Description = "5 mg / 5ml jarabe de 100ml",
                            Discount = 0,
                            Id_Category = 2,
                            Id_MedicineBrand = 7,
                            Id_Presentation = 2,
                            Name = "Loratadina",
                            Need_order = true,
                            Price = 22
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Order")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_expiration")
                        .HasColumnType("DateTime")
                        .HasColumnName("Expire_Date");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("EpsId")
                        .HasColumnType("int");

                    b.Property<int>("Id_sale")
                        .HasColumnType("int");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("DateTime")
                        .HasColumnName("Order_Date");

                    b.HasKey("Id");

                    b.HasIndex("EpsId");

                    b.HasIndex("Id_sale");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Person")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("DateTime")
                        .HasColumnName("Birth_Date");

                    b.Property<int>("Id_Document_type")
                        .HasColumnType("int");

                    b.Property<int>("Id_Type_Person")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("Register_date")
                        .HasMaxLength(60)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Register_Date");

                    b.HasKey("Id");

                    b.HasIndex("Id_Document_type");

                    b.HasIndex("Id_Type_Person");

                    b.ToTable("Person", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6389),
                            Id_Document_type = 3,
                            Id_Type_Person = 1,
                            Name = "root",
                            Register_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6377)
                        },
                        new
                        {
                            Id = 2,
                            Birth_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6390),
                            Id_Document_type = 3,
                            Id_Type_Person = 2,
                            Name = "ProveedorA",
                            Register_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6390)
                        },
                        new
                        {
                            Id = 3,
                            Birth_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6391),
                            Id_Document_type = 3,
                            Id_Type_Person = 2,
                            Name = "ProveedorB",
                            Register_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6391)
                        },
                        new
                        {
                            Id = 4,
                            Birth_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6393),
                            Id_Document_type = 3,
                            Id_Type_Person = 2,
                            Name = "ProveedorC",
                            Register_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6392)
                        },
                        new
                        {
                            Id = 5,
                            Birth_date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Document_type = 1,
                            Id_Type_Person = 1,
                            Name = "Juan Paco",
                            Register_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6393)
                        },
                        new
                        {
                            Id = 6,
                            Birth_date = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Document_type = 1,
                            Id_Type_Person = 1,
                            Name = "Pedro De La Mar",
                            Register_date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Birth_date = new DateTime(2014, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Document_type = 2,
                            Id_Type_Person = 1,
                            Name = "Maria Db",
                            Register_date = new DateTime(2023, 9, 27, 22, 38, 15, 296, DateTimeKind.Local).AddTicks(6400)
                        },
                        new
                        {
                            Id = 8,
                            Birth_date = new DateTime(1929, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Document_type = 1,
                            Id_Type_Person = 1,
                            Name = "Ana frank",
                            Register_date = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Birth_date = new DateTime(1978, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Document_type = 1,
                            Id_Type_Person = 1,
                            Name = "Luis Fonsi",
                            Register_date = new DateTime(2018, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Birth_date = new DateTime(1957, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Document_type = 1,
                            Id_Type_Person = 1,
                            Name = "Sena Sofia",
                            Register_date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Birth_date = new DateTime(1987, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Document_type = 1,
                            Id_Type_Person = 1,
                            Name = "Elena de avalord",
                            Register_date = new DateTime(2001, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Position")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Position", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "seller"
                        },
                        new
                        {
                            Id = 2,
                            Name = "manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Presentation")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Presentation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tableta"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cápsula"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jarabe"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Provider")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ProviderTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProviderTypeId");

                    b.ToTable("Provider", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "melissa",
                            PersonId = 2,
                            ProviderTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "benito",
                            PersonId = 3,
                            ProviderTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "MQ society",
                            PersonId = 4,
                            ProviderTypeId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPk")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Employee"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role_user", b =>
                {
                    b.Property<int>("Id_user")
                        .HasColumnType("int");

                    b.Property<int>("Id_role")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id_user", "Id_role");

                    b.HasIndex("Id_role");

                    b.ToTable("RoleUser", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Sale")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Employe")
                        .HasColumnType("int");

                    b.Property<int>("Id_person")
                        .HasColumnType("int");

                    b.Property<DateTime>("Sale_Date")
                        .HasColumnType("Datetime")
                        .HasColumnName("Sale_Date");

                    b.HasKey("Id");

                    b.HasIndex("Id_Employe");

                    b.HasIndex("Id_person");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_State")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("State", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "prueba"
                        },
                        new
                        {
                            Id = 2,
                            Name = "prueba"
                        },
                        new
                        {
                            Id = 3,
                            Name = "prueba"
                        },
                        new
                        {
                            Id = 4,
                            Name = "prueba"
                        },
                        new
                        {
                            Id = 5,
                            Name = "prueba"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Type_eps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_type_eps")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Type_eps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Type_person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_type_person")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("Type_person", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Natural"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Juridica"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Type_provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_type_provider")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Type_provider", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drugs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "syrups"
                        },
                        new
                        {
                            Id = 3,
                            Name = "hallucinogens"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPk")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("AccessToken");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Password");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("RefreshToken");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("UserName", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Username_Email");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "root",
                            PersonId = 1,
                            UserName = "root"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Address", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("Id_City")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("Id_person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Buy", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Buys")
                        .HasForeignKey("Employee_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Provider", "Provider")
                        .WithMany("Buys")
                        .HasForeignKey("Provider_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Cities")
                        .HasForeignKey("Id_department")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.HasOne("Domain.Entities.Contact_category", "Contact_Category")
                        .WithMany("Contacts")
                        .HasForeignKey("Id_contact_category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Contact_Type", "Contact_Type")
                        .WithMany("Contacts")
                        .HasForeignKey("Id_contact_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("Id_person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact_Category");

                    b.Navigation("Contact_Type");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Departments")
                        .HasForeignKey("Id_country")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Detail_buy", b =>
                {
                    b.HasOne("Domain.Entities.Buy", "Buy")
                        .WithMany("Detail_Buys")
                        .HasForeignKey("Buy_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Medicine", "Medicine")
                        .WithMany("Detail_Buys")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buy");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("Domain.Entities.Detail_sale", b =>
                {
                    b.HasOne("Domain.Entities.Medicine", "Medicine")
                        .WithMany("Detail_Sales")
                        .HasForeignKey("Id_medicine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "Sale")
                        .WithMany("Detail_Sales")
                        .HasForeignKey("Id_sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Employees")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Domain.Entities.Employee_eps", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Employee_Epss")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Eps", "Eps")
                        .WithMany("Employee_Epss")
                        .HasForeignKey("EpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Eps");
                });

            modelBuilder.Entity("Domain.Entities.Eps", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Epss")
                        .HasForeignKey("Id_Person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Type_eps", "Type_Eps")
                        .WithMany("Epss")
                        .HasForeignKey("Id_type_eps")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Type_Eps");
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Domain.Entities.Medicine_info", "Medicine_info")
                        .WithMany("Inventories")
                        .HasForeignKey("Id_MedicineInfo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine_info");
                });

            modelBuilder.Entity("Domain.Entities.Medicine", b =>
                {
                    b.HasOne("Domain.Entities.Inventory", "Inventory")
                        .WithMany("Medicines")
                        .HasForeignKey("Id_Inventory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.State", "State")
                        .WithMany("Medicines")
                        .HasForeignKey("Id_state")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Domain.Entities.Medicine_info", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Medicine_Infos")
                        .HasForeignKey("Id_Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Medicine_brand", "Medicine_brand")
                        .WithMany("Medicine_Infos")
                        .HasForeignKey("Id_MedicineBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Presentation", "Presentation")
                        .WithMany("Medicine_Infos")
                        .HasForeignKey("Id_Presentation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Medicine_brand");

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Eps", "Eps")
                        .WithMany("Orders")
                        .HasForeignKey("EpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "Sale")
                        .WithMany("Orders")
                        .HasForeignKey("Id_sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eps");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.HasOne("Domain.Entities.Document_type", "Document_type")
                        .WithMany("Persons")
                        .HasForeignKey("Id_Document_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Type_person", "Type_Person")
                        .WithMany("Persons")
                        .HasForeignKey("Id_Type_Person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document_type");

                    b.Navigation("Type_Person");
                });

            modelBuilder.Entity("Domain.Entities.Provider", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Providers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Type_provider", "Type_Provider")
                        .WithMany("Providers")
                        .HasForeignKey("ProviderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Type_Provider");
                });

            modelBuilder.Entity("Domain.Entities.Role_user", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Role_Users")
                        .HasForeignKey("Id_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Role_users")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("Id_Employe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Sales")
                        .HasForeignKey("Id_person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithMany("Users")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Buy", b =>
                {
                    b.Navigation("Detail_Buys");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Medicine_Infos");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Domain.Entities.Contact_Type", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Domain.Entities.Contact_category", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Domain.Entities.Document_type", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Buys");

                    b.Navigation("Employee_Epss");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Domain.Entities.Eps", b =>
                {
                    b.Navigation("Employee_Epss");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("Domain.Entities.Medicine", b =>
                {
                    b.Navigation("Detail_Buys");

                    b.Navigation("Detail_Sales");
                });

            modelBuilder.Entity("Domain.Entities.Medicine_brand", b =>
                {
                    b.Navigation("Medicine_Infos");
                });

            modelBuilder.Entity("Domain.Entities.Medicine_info", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("Employees");

                    b.Navigation("Epss");

                    b.Navigation("Providers");

                    b.Navigation("Sales");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Presentation", b =>
                {
                    b.Navigation("Medicine_Infos");
                });

            modelBuilder.Entity("Domain.Entities.Provider", b =>
                {
                    b.Navigation("Buys");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Role_Users");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("Detail_Sales");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.State", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("Domain.Entities.Type_eps", b =>
                {
                    b.Navigation("Epss");
                });

            modelBuilder.Entity("Domain.Entities.Type_person", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Domain.Entities.Type_provider", b =>
                {
                    b.Navigation("Providers");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Role_users");
                });
#pragma warning restore 612, 618
        }
    }
}
